import { Type, type Static } from "@sinclair/typebox";

export const ProblemCodeSchema = Type.Union([
  Type.Literal("AUTH_REQUIRED"),
  Type.Literal("AUTH_INVALID"),
  Type.Literal("DEVICE_NOT_OWNED"),
  Type.Literal("DEVICE_REVOKED"),
  Type.Literal("DEVICE_NOT_PARTICIPANT"),
  Type.Literal("INSTALLATION_OWNED_BY_ANOTHER_USER"),
  Type.Literal("IDEMPOTENCY_CONFLICT"),
  Type.Literal("INVALID_REQUEST"),
  Type.Literal("RATE_LIMITED"),
  Type.Literal("TRIP_STORAGE_LIMIT"),
  Type.Literal("ACTIVE_TRIP_EXISTS"),
  Type.Literal("TRIP_ID_CONFLICT"),
  Type.Literal("TRIP_DURATION_INVALID"),
  Type.Literal("INVITE_CODE_CONFLICT"),
  Type.Literal("TRIP_FULL"),
  Type.Literal("INVITE_INVALID"),
  Type.Literal("TRIP_OWNER_REQUIRED"),
  Type.Literal("MEMBERSHIP_FROZEN"),
  Type.Literal("PENDING_JOIN_REQUESTS"),
  Type.Literal("KEY_ENVELOPE_MISSING"),
  Type.Literal("KEY_ENVELOPE_INVALID"),
  Type.Literal("PHOTO_LIBRARY_ACCESS_REQUIRED"),
  Type.Literal("TRIP_STATE_CONFLICT"),
  Type.Literal("VERSION_CONFLICT"),
  Type.Literal("UPLOAD_EXPIRED"),
  Type.Literal("OBJECT_MISMATCH"),
  Type.Literal("CURSOR_EXPIRED"),
  Type.Literal("NOT_FOUND"),
  Type.Literal("CONFLICT"),
  Type.Literal("INTERNAL_ERROR"),
]);
export type ProblemCode = Static<typeof ProblemCodeSchema>;
