import {
  DOMAIN_SCHEMA_VERSION,
  INVITE_VERSION,
  MAX_GROUP_SECRET_CHARS,
  MAX_INVITE_LIFETIME_MS,
  MIN_GROUP_SECRET_CHARS,
  PROTOCOL_VERSION,
  type DomainSchemaVersion,
  type InviteVersion,
  type ProtocolVersion,
} from "./constants";
import {
  parseDeviceId,
  parseIdentityPublicKey,
  parseInviteId,
  parseMemberId,
  parseTripId,
  type DeviceId,
  type IdentityPublicKey,
  type InviteId,
  type MemberId,
  type TripId,
} from "./ids";
import {
  appendResult,
  issue,
  parseFailure,
  parseSuccess,
  readNumber,
  readString,
  rejectUnknownKeys,
  requireRecord,
  type ParseResult,
  type ValidationIssue,
} from "./validation";

declare const groupSecretBrand: unique symbol;
export type GroupSecret = string & { readonly [groupSecretBrand]: "GroupSecret" };

export interface TripInvite {
  readonly schemaVersion: DomainSchemaVersion;
  readonly inviteVersion: InviteVersion;
  readonly protocolVersion: ProtocolVersion;
  readonly tripId: TripId;
  readonly inviteId: InviteId;
  readonly inviterMemberId: MemberId;
  readonly inviterDeviceId: DeviceId;
  readonly inviterIdentityPublicKey: IdentityPublicKey;
  readonly membershipEpoch: number;
  readonly issuedAtMs: number;
  readonly expiresAtMs: number;
  /** Ed25519 signature over the canonical invite payload. */
  readonly signature: string;
  /**
   * High-entropy base64url secret used by an audited adapter to establish trip
   * keys. It must be generated by a platform CSPRNG. This core never generates
   * secrets and callers must never log an invite URI.
   */
  readonly groupSecret: GroupSecret;
  /** Optional transport discovery hint; never treated as authentication. */
  readonly endpointHint: string | null;
}

export interface DecodeInviteOptions {
  readonly nowMs?: number;
  readonly expectedTripId?: TripId;
  /** HTTPS invite origins accepted in addition to airmesh://join. */
  readonly allowedHttpsOrigins?: readonly string[];
}

export interface EncodeInviteOptions {
  /** Defaults to airmesh://join. An HTTPS base must end in /join. */
  readonly baseUrl?: string;
}

const INVITE_KEYS = [
  "schemaVersion",
  "inviteVersion",
  "protocolVersion",
  "tripId",
  "inviteId",
  "inviterMemberId",
  "inviterDeviceId",
  "inviterIdentityPublicKey",
  "membershipEpoch",
  "issuedAtMs",
  "expiresAtMs",
  "signature",
  "groupSecret",
  "endpointHint",
] as const;

const QUERY_KEYS = [
  "sv",
  "iv",
  "pv",
  "trip",
  "invite",
  "member",
  "device",
  "identity",
  "epoch",
  "issued",
  "expires",
  "signature",
  "secret",
  "endpoint",
] as const;

const BASE64URL_PATTERN = /^[A-Za-z0-9_-]+$/;
// A canonical unpadded 32-byte base64url value has four significant bits in
// its final character, so the final six-bit symbol must be a multiple of four.
const CANONICAL_32_BYTE_BASE64URL_PATTERN = /^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/;

export function parseGroupSecret(value: unknown): ParseResult<GroupSecret> {
  if (
    typeof value !== "string" ||
    value.length < MIN_GROUP_SECRET_CHARS ||
    value.length > MAX_GROUP_SECRET_CHARS ||
    !BASE64URL_PATTERN.test(value) ||
    !CANONICAL_32_BYTE_BASE64URL_PATTERN.test(value)
  ) {
    return parseFailure([
      issue(
        "$",
        "INVALID_GROUP_SECRET",
        `Group secret must be a canonical ${MIN_GROUP_SECRET_CHARS}-character base64url encoding of 32 CSPRNG bytes.`,
      ),
    ]);
  }
  return parseSuccess(value as GroupSecret);
}

export function parseTripInvite(value: unknown): ParseResult<TripInvite> {
  const issues: ValidationIssue[] = [];
  const record = requireRecord(value, "$", issues);
  if (record === undefined) return parseFailure(issues);
  rejectUnknownKeys(record, INVITE_KEYS, "$", issues);

  const schemaVersion = readNumber(record, "schemaVersion", "$", issues, {
    integer: true,
    safeInteger: true,
    min: DOMAIN_SCHEMA_VERSION,
    max: DOMAIN_SCHEMA_VERSION,
  });
  const inviteVersion = readNumber(record, "inviteVersion", "$", issues, {
    integer: true,
    safeInteger: true,
    min: INVITE_VERSION,
    max: INVITE_VERSION,
  });
  const protocolVersion = readNumber(record, "protocolVersion", "$", issues, {
    integer: true,
    safeInteger: true,
    min: PROTOCOL_VERSION,
    max: PROTOCOL_VERSION,
  });
  const tripId = appendResult(parseTripId(record.tripId), issues, "tripId");
  const inviteId = appendResult(parseInviteId(record.inviteId), issues, "inviteId");
  const inviterMemberId = appendResult(
    parseMemberId(record.inviterMemberId),
    issues,
    "inviterMemberId",
  );
  const inviterDeviceId = appendResult(
    parseDeviceId(record.inviterDeviceId),
    issues,
    "inviterDeviceId",
  );
  const inviterIdentityPublicKey = appendResult(
    parseIdentityPublicKey(record.inviterIdentityPublicKey),
    issues,
    "inviterIdentityPublicKey",
  );
  const membershipEpoch = readNumber(record, "membershipEpoch", "$", issues, {
    integer: true,
    safeInteger: true,
    min: 0,
  });
  const issuedAtMs = readNumber(record, "issuedAtMs", "$", issues, {
    integer: true,
    safeInteger: true,
    min: 0,
  });
  const expiresAtMs = readNumber(record, "expiresAtMs", "$", issues, {
    integer: true,
    safeInteger: true,
    min: 0,
  });
  const signature = readString(record, "signature", "$", issues, {
    minLength: 86,
    maxLength: 86,
    pattern: BASE64URL_PATTERN,
  });
  const groupSecret = appendResult(
    parseGroupSecret(record.groupSecret),
    issues,
    "groupSecret",
  );
  const endpointHint = readRequiredNullableString(
    record,
    "endpointHint",
    issues,
    256,
  );

  if (issuedAtMs !== undefined && expiresAtMs !== undefined) {
    if (expiresAtMs <= issuedAtMs) {
      issues.push(issue("expiresAtMs", "INVALID_EXPIRY", "Invite must expire after issuance."));
    } else if (expiresAtMs - issuedAtMs > MAX_INVITE_LIFETIME_MS) {
      issues.push(
        issue(
          "expiresAtMs",
          "INVITE_LIFETIME_TOO_LONG",
          `Invite lifetime cannot exceed ${MAX_INVITE_LIFETIME_MS} ms.`,
        ),
      );
    }
  }
  if (issues.length > 0) return parseFailure(issues);

  return parseSuccess({
    schemaVersion: schemaVersion as DomainSchemaVersion,
    inviteVersion: inviteVersion as InviteVersion,
    protocolVersion: protocolVersion as ProtocolVersion,
    tripId: tripId!,
    inviteId: inviteId!,
    inviterMemberId: inviterMemberId!,
    inviterDeviceId: inviterDeviceId!,
    inviterIdentityPublicKey: inviterIdentityPublicKey!,
    membershipEpoch: membershipEpoch!,
    issuedAtMs: issuedAtMs!,
    expiresAtMs: expiresAtMs!,
    signature: signature!,
    groupSecret: groupSecret!,
    endpointHint: endpointHint!,
  });
}

export function validateInviteForJoin(
  invite: TripInvite,
  nowMs: number,
  expectedTripId?: TripId,
): readonly ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  if (!Number.isSafeInteger(nowMs) || nowMs < 0) {
    issues.push(issue("nowMs", "INVALID_TIME", "Current time must be a non-negative safe integer."));
    return issues;
  }
  if (invite.expiresAtMs <= nowMs) {
    issues.push(issue("expiresAtMs", "INVITE_EXPIRED", "Invite has expired."));
  }
  // Reject invites issued implausibly far in the future while tolerating clock skew.
  if (invite.issuedAtMs > nowMs + 5 * 60 * 1000) {
    issues.push(issue("issuedAtMs", "INVITE_NOT_YET_VALID", "Invite issuance time is in the future."));
  }
  if (expectedTripId !== undefined && invite.tripId !== expectedTripId) {
    issues.push(issue("tripId", "TRIP_MISMATCH", "Invite belongs to another trip."));
  }
  return issues;
}

export function encodeInviteDeepLink(
  inviteValue: TripInvite,
  options: EncodeInviteOptions = {},
): string {
  const parsed = parseTripInvite(inviteValue);
  if (!parsed.ok) {
    throw new Error(`Cannot encode invalid invite: ${parsed.issues.map((entry) => entry.path).join(", ")}`);
  }
  const url = parseInviteBaseUrl(options.baseUrl ?? "airmesh://join");
  const invite = parsed.value;
  url.searchParams.set("sv", String(invite.schemaVersion));
  url.searchParams.set("iv", String(invite.inviteVersion));
  url.searchParams.set("pv", String(invite.protocolVersion));
  url.searchParams.set("trip", invite.tripId);
  url.searchParams.set("invite", invite.inviteId);
  url.searchParams.set("member", invite.inviterMemberId);
  url.searchParams.set("device", invite.inviterDeviceId);
  url.searchParams.set("identity", invite.inviterIdentityPublicKey);
  url.searchParams.set("epoch", String(invite.membershipEpoch));
  url.searchParams.set("issued", String(invite.issuedAtMs));
  url.searchParams.set("expires", String(invite.expiresAtMs));
  url.searchParams.set("signature", invite.signature);
  url.searchParams.set("secret", invite.groupSecret);
  if (invite.endpointHint !== null) url.searchParams.set("endpoint", invite.endpointHint);
  return url.toString();
}

export function decodeInviteDeepLink(
  value: string,
  options: DecodeInviteOptions = {},
): ParseResult<TripInvite> {
  if (value.length > 4_096) {
    return parseFailure([
      issue("$", "URL_TOO_LONG", "Invite URL exceeds the 4096-character limit."),
    ]);
  }
  const issues: ValidationIssue[] = [];
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return parseFailure([issue("$", "INVALID_URL", "Invite is not a valid URL.")]);
  }

  if (url.username !== "" || url.password !== "" || url.hash !== "") {
    issues.push(issue("$", "INVALID_URL", "Invite URL cannot contain credentials or a fragment."));
  }
  if (!isAllowedInviteUrl(url, options.allowedHttpsOrigins ?? [])) {
    issues.push(issue("$", "UNTRUSTED_INVITE_ORIGIN", "Invite URL origin or path is not allowed."));
  }

  const known = new Set<string>(QUERY_KEYS);
  for (const key of url.searchParams.keys()) {
    if (!known.has(key)) {
      issues.push(issue(`query.${key}`, "UNKNOWN_FIELD", "Unexpected invite parameter."));
    }
  }
  for (const key of QUERY_KEYS) {
    if (url.searchParams.getAll(key).length > 1) {
      issues.push(issue(`query.${key}`, "DUPLICATE_FIELD", "Invite parameter must appear at most once."));
    }
  }
  if (issues.length > 0) return parseFailure(issues);

  const rawInvite: Record<string, unknown> = {
    schemaVersion: parseDecimalParameter(url, "sv", issues),
    inviteVersion: parseDecimalParameter(url, "iv", issues),
    protocolVersion: parseDecimalParameter(url, "pv", issues),
    tripId: requireParameter(url, "trip", issues),
    inviteId: requireParameter(url, "invite", issues),
    inviterMemberId: requireParameter(url, "member", issues),
    inviterDeviceId: requireParameter(url, "device", issues),
    inviterIdentityPublicKey: requireParameter(url, "identity", issues),
    membershipEpoch: parseDecimalParameter(url, "epoch", issues),
    issuedAtMs: parseDecimalParameter(url, "issued", issues),
    expiresAtMs: parseDecimalParameter(url, "expires", issues),
    signature: requireParameter(url, "signature", issues),
    groupSecret: requireParameter(url, "secret", issues),
    endpointHint: url.searchParams.get("endpoint"),
  };
  if (issues.length > 0) return parseFailure(issues);

  const parsed = parseTripInvite(rawInvite);
  if (!parsed.ok) return parsed;
  if (options.nowMs !== undefined) {
    const joinIssues = validateInviteForJoin(parsed.value, options.nowMs, options.expectedTripId);
    if (joinIssues.length > 0) return parseFailure(joinIssues);
  }
  return parsed;
}

function parseInviteBaseUrl(value: string): URL {
  const url = new URL(value);
  if (!isAllowedInviteUrl(url, [url.origin])) {
    throw new Error("Invite base must be airmesh://join or an HTTPS URL ending in /join.");
  }
  url.search = "";
  url.hash = "";
  return url;
}

function isAllowedInviteUrl(url: URL, allowedHttpsOrigins: readonly string[]): boolean {
  if (
    url.protocol === "airmesh:" &&
    url.hostname === "join" &&
    (url.pathname === "" || url.pathname === "/")
  ) {
    return true;
  }
  if (url.protocol !== "https:" || url.pathname !== "/join") return false;
  return allowedHttpsOrigins.some((origin) => {
    try {
      return new URL(origin).origin === url.origin;
    } catch {
      return false;
    }
  });
}

function requireParameter(
  url: URL,
  key: string,
  issues: ValidationIssue[],
): string | undefined {
  const value = url.searchParams.get(key);
  if (value === null || value.length === 0) {
    issues.push(issue(`query.${key}`, "REQUIRED", "Invite parameter is required."));
    return undefined;
  }
  return value;
}

function parseDecimalParameter(
  url: URL,
  key: string,
  issues: ValidationIssue[],
): number | undefined {
  const value = requireParameter(url, key, issues);
  if (value === undefined) return undefined;
  if (!/^(0|[1-9]\d*)$/.test(value)) {
    issues.push(issue(`query.${key}`, "INVALID_INTEGER", "Expected a canonical decimal integer."));
    return undefined;
  }
  const result = Number(value);
  if (!Number.isSafeInteger(result)) {
    issues.push(issue(`query.${key}`, "INVALID_INTEGER", "Integer exceeds the safe range."));
    return undefined;
  }
  return result;
}

function readRequiredNullableString(
  record: Record<string, unknown>,
  key: string,
  issues: ValidationIssue[],
  maxLength: number,
): string | null | undefined {
  if (!(key in record)) {
    issues.push(issue(key, "REQUIRED", "Field is required."));
    return undefined;
  }
  if (record[key] === null) return null;
  return readString(record, key, "$", issues, {
    minLength: 1,
    maxLength,
    requireTrimmed: true,
  });
}
