/* This file is generated by tools/generate-mobile-api.mjs. */
import type { ApproveJoinRequestBody, CreateJoinRequestBody, CreateTripBody, DeviceResponse, MembershipResponse, RegisterDeviceBody, StartTripBody, TripResponse } from "@crewroll/contracts";

export type MobileOperationId = "approveJoinRequest" | "createJoinRequest" | "createTrip" | "getTrip" | "registerDevice" | "startTrip";

export type MobileOperationMap = {
  approveJoinRequest: {
    method: "PUT";
    path: "/v1/trips/{tripId}/join-requests/{membershipId}/approval";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: ApproveJoinRequestBody;
    response: MembershipResponse;
  };
  createJoinRequest: {
    method: "POST";
    path: "/v1/trips/join-requests";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateJoinRequestBody;
    response: MembershipResponse;
  };
  createTrip: {
    method: "POST";
    path: "/v1/trips";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateTripBody;
    response: TripResponse;
  };
  getTrip: {
    method: "GET";
    path: "/v1/trips/{tripId}";
    headers: "X-CrewRoll-Device-Id";
    response: TripResponse;
  };
  registerDevice: {
    method: "POST";
    path: "/v1/devices";
    headers: "Idempotency-Key";
    request: RegisterDeviceBody;
    response: DeviceResponse;
  };
  startTrip: {
    method: "POST";
    path: "/v1/trips/{tripId}/start";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: StartTripBody;
    response: TripResponse;
  };
};
