/* This file is generated by tools/generate-mobile-api.mjs. */
import type { AccountPolicy, AcceptTermsBody, DeleteAccountBody, AccountDeletion, SafetyReportBody, SafetyReportResponse, BlockMemberBody, BlockedMembers, AccountActionResponse, TripContinuity, TripContinuityBody, TripListResponse, TripLifecycleBody, TripTransferState, ApproveJoinRequestBody, CreateJoinRequestBody, CreateTripBody, CreateTripOutcomeBody, CreateTripOutcomeResponse, DeviceResponse, MembershipResponse, InvitePreviewBody, InvitePreviewResponse, ProblemDetails, ProfileResponse, RegisterDeviceBody, SetTripReadinessBody, StartTripBody, SyncProfileBody, TripResponse } from "@crewroll/contracts";

export type MobileOperationId = "getAccountPolicy" | "acceptAccountTerms" | "requestAccountDeletion" | "reportSafetyIssue" | "getBlockedMembers" | "blockMember" | "unblockMember" | "getTripContinuity" | "changeTripContinuity" | "listTrips" | "getTripLifecycle" | "changeTripLifecycle" | "approveJoinRequest" | "rejectJoinRequest" | "createJoinRequest" | "createTrip" | "getTrip" | "previewInvite" | "registerDevice" | "resolveCreateTripOutcome" | "setTripReadiness" | "startTrip" | "syncProfile";

export type MobilePaths = {
  "/v1/account": {
    get: {
      parameters: {
      };
      responses: {
        200: {
          content: {
            "application/json": AccountPolicy;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/account/terms": {
    put: {
      parameters: {
      };
      requestBody: {
        content: {
          "application/json": AcceptTermsBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": AccountPolicy;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/account/deletion": {
    post: {
      parameters: {
      };
      requestBody: {
        content: {
          "application/json": DeleteAccountBody;
        };
      };
      responses: {
        202: {
          content: {
            "application/json": AccountDeletion;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/account/reports": {
    post: {
      parameters: {
      };
      requestBody: {
        content: {
          "application/json": SafetyReportBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": SafetyReportResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/account/blocks": {
    get: {
      parameters: {
      };
      responses: {
        200: {
          content: {
            "application/json": BlockedMembers;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
    post: {
      parameters: {
      };
      requestBody: {
        content: {
          "application/json": BlockMemberBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": AccountActionResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/account/blocks/{userId}": {
    delete: {
      parameters: {
        path: {
          "userId": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": AccountActionResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/continuity": {
    get: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
        path: {
          "tripId": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripContinuity;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": TripContinuityBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripContinuity;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips": {
    get: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripListResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateTripBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/lifecycle": {
    get: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
        path: {
          "tripId": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripTransferState;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": TripLifecycleBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripTransferState;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/profile": {
    put: {
      parameters: {
      };
      requestBody: {
        content: {
          "application/json": SyncProfileBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": ProfileResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/invite-preview": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
      };
      requestBody: {
        content: {
          "application/json": InvitePreviewBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": InvitePreviewResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/join-requests/{membershipId}/approval": {
    put: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
          "membershipId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": ApproveJoinRequestBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": MembershipResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/join-requests/{membershipId}": {
    delete: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
          "membershipId": string;
        };
      };
      responses: {
        204: {
          content?: never;
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/join-requests": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateJoinRequestBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": MembershipResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}": {
    get: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
        path: {
          "tripId": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/devices": {
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": RegisterDeviceBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": DeviceResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/create-outcome": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateTripOutcomeBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": CreateTripOutcomeResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/readiness": {
    put: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": SetTripReadinessBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/start": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": StartTripBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
};

export type MobileOperationMap = {
  getAccountPolicy: {
    method: "GET";
    path: "/v1/account";
    headers: never;
    response: AccountPolicy;
  };
  acceptAccountTerms: {
    method: "PUT";
    path: "/v1/account/terms";
    headers: never;
    request: AcceptTermsBody;
    response: AccountPolicy;
  };
  requestAccountDeletion: {
    method: "POST";
    path: "/v1/account/deletion";
    headers: never;
    request: DeleteAccountBody;
    response: AccountDeletion;
  };
  reportSafetyIssue: {
    method: "POST";
    path: "/v1/account/reports";
    headers: never;
    request: SafetyReportBody;
    response: SafetyReportResponse;
  };
  getBlockedMembers: {
    method: "GET";
    path: "/v1/account/blocks";
    headers: never;
    response: BlockedMembers;
  };
  blockMember: {
    method: "POST";
    path: "/v1/account/blocks";
    headers: never;
    request: BlockMemberBody;
    response: AccountActionResponse;
  };
  unblockMember: {
    method: "DELETE";
    path: "/v1/account/blocks/{userId}";
    headers: never;
    response: AccountActionResponse;
  };
  getTripContinuity: {
    method: "GET";
    path: "/v1/trips/{tripId}/continuity";
    headers: "X-CrewRoll-Device-Id";
    response: TripContinuity;
  };
  changeTripContinuity: {
    method: "POST";
    path: "/v1/trips/{tripId}/continuity";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: TripContinuityBody;
    response: TripContinuity;
  };
  listTrips: {
    method: "GET";
    path: "/v1/trips";
    headers: "X-CrewRoll-Device-Id";
    response: TripListResponse;
  };
  getTripLifecycle: {
    method: "GET";
    path: "/v1/trips/{tripId}/lifecycle";
    headers: "X-CrewRoll-Device-Id";
    response: TripTransferState;
  };
  changeTripLifecycle: {
    method: "POST";
    path: "/v1/trips/{tripId}/lifecycle";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: TripLifecycleBody;
    response: TripTransferState;
  };
  syncProfile: {
    method: "PUT";
    path: "/v1/profile";
    headers: never;
    request: SyncProfileBody;
    response: ProfileResponse;
  };
  previewInvite: {
    method: "POST";
    path: "/v1/trips/invite-preview";
    headers: "X-CrewRoll-Device-Id";
    request: InvitePreviewBody;
    response: InvitePreviewResponse;
  };
  approveJoinRequest: {
    method: "PUT";
    path: "/v1/trips/{tripId}/join-requests/{membershipId}/approval";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: ApproveJoinRequestBody;
    response: MembershipResponse;
  };
  rejectJoinRequest: {
    method: "DELETE";
    path: "/v1/trips/{tripId}/join-requests/{membershipId}";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    response: void;
  };
  createJoinRequest: {
    method: "POST";
    path: "/v1/trips/join-requests";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateJoinRequestBody;
    response: MembershipResponse;
  };
  createTrip: {
    method: "POST";
    path: "/v1/trips";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateTripBody;
    response: TripResponse;
  };
  getTrip: {
    method: "GET";
    path: "/v1/trips/{tripId}";
    headers: "X-CrewRoll-Device-Id";
    response: TripResponse;
  };
  registerDevice: {
    method: "POST";
    path: "/v1/devices";
    headers: "Idempotency-Key";
    request: RegisterDeviceBody;
    response: DeviceResponse;
  };
  resolveCreateTripOutcome: {
    method: "POST";
    path: "/v1/trips/create-outcome";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateTripOutcomeBody;
    response: CreateTripOutcomeResponse;
  };
  setTripReadiness: {
    method: "PUT";
    path: "/v1/trips/{tripId}/readiness";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: SetTripReadinessBody;
    response: TripResponse;
  };
  startTrip: {
    method: "POST";
    path: "/v1/trips/{tripId}/start";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: StartTripBody;
    response: TripResponse;
  };
};
