/* This file is generated by tools/generate-mobile-api.mjs. */
import type { ApproveJoinRequestBody, CreateJoinRequestBody, CreateTripBody, CreateTripOutcomeBody, CreateTripOutcomeResponse, DeviceResponse, MembershipResponse, InvitePreviewBody, InvitePreviewResponse, ProblemDetails, RegisterDeviceBody, SetTripReadinessBody, StartTripBody, TripResponse } from "@crewroll/contracts";

export type MobileOperationId = "approveJoinRequest" | "createJoinRequest" | "createTrip" | "getTrip" | "previewInvite" | "registerDevice" | "resolveCreateTripOutcome" | "setTripReadiness" | "startTrip";

export type MobilePaths = {
  "/v1/trips/invite-preview": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
      };
      requestBody: {
        content: {
          "application/json": InvitePreviewBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": InvitePreviewResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/join-requests/{membershipId}/approval": {
    put: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
          "membershipId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": ApproveJoinRequestBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": MembershipResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/join-requests": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateJoinRequestBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": MembershipResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateTripBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}": {
    get: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
        };
        path: {
          "tripId": string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/devices": {
    post: {
      parameters: {
        header: {
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": RegisterDeviceBody;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": DeviceResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/create-outcome": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
      };
      requestBody: {
        content: {
          "application/json": CreateTripOutcomeBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": CreateTripOutcomeResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/readiness": {
    put: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": SetTripReadinessBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
  "/v1/trips/{tripId}/start": {
    post: {
      parameters: {
        header: {
          "X-CrewRoll-Device-Id": string;
          "Idempotency-Key": string;
        };
        path: {
          "tripId": string;
        };
      };
      requestBody: {
        content: {
          "application/json": StartTripBody;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": TripResponse;
          };
        };
        400: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        401: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        403: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        404: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        409: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        429: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
        500: {
          content: {
            "application/problem+json": ProblemDetails;
          };
        };
      };
    };
  };
};

export type MobileOperationMap = {
  previewInvite: {
    method: "POST";
    path: "/v1/trips/invite-preview";
    headers: "X-CrewRoll-Device-Id";
    request: InvitePreviewBody;
    response: InvitePreviewResponse;
  };
  approveJoinRequest: {
    method: "PUT";
    path: "/v1/trips/{tripId}/join-requests/{membershipId}/approval";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: ApproveJoinRequestBody;
    response: MembershipResponse;
  };
  createJoinRequest: {
    method: "POST";
    path: "/v1/trips/join-requests";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateJoinRequestBody;
    response: MembershipResponse;
  };
  createTrip: {
    method: "POST";
    path: "/v1/trips";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateTripBody;
    response: TripResponse;
  };
  getTrip: {
    method: "GET";
    path: "/v1/trips/{tripId}";
    headers: "X-CrewRoll-Device-Id";
    response: TripResponse;
  };
  registerDevice: {
    method: "POST";
    path: "/v1/devices";
    headers: "Idempotency-Key";
    request: RegisterDeviceBody;
    response: DeviceResponse;
  };
  resolveCreateTripOutcome: {
    method: "POST";
    path: "/v1/trips/create-outcome";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: CreateTripOutcomeBody;
    response: CreateTripOutcomeResponse;
  };
  setTripReadiness: {
    method: "PUT";
    path: "/v1/trips/{tripId}/readiness";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: SetTripReadinessBody;
    response: TripResponse;
  };
  startTrip: {
    method: "POST";
    path: "/v1/trips/{tripId}/start";
    headers: "X-CrewRoll-Device-Id" | "Idempotency-Key";
    request: StartTripBody;
    response: TripResponse;
  };
};
